---
# install Graylog by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Create Graylog User
  user:
    name: graylog
    shell: /bin/bash

- name: Create Graylog dir
  file: 
    path: "{{item}}"
    state: directory
    owner: graylog
    group: graylog
    mode: '0750'
  with_items:
    - /data/wwwroot/graylog

- name: Set graylog config
  lineinfile:
    dest: /etc/graylog/server/server.conf
    regexp: '{{item.regexp}}'
    line: '{{item.replace}}'
  loop:
    - {regexp: password_secret =,replace: password_secret = I5EyvUWiQVAhyw1pPjkYlYHowCtqoEsxJOPIxh13A0yFJYoUmMUnGe9wNbomvtUiX1jFkWYYIVW0Q1PadZCG1aaGowJoMRpd}
    - {regexp: \#root_username = admin,replace: root_username = admin}
    - {regexp: root_password_sha2 =,replace: root_password_sha2 = 240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9}

- name: Internal huwei cloud support
  shell: sudo sed -i 's/#http_bind_address = 127.0.0.1:9000/http_bind_address = 0.0.0.0:9000/g' /etc/graylog/server/server.conf

- name: Start Graylog and restart Nginx
  service:
    name: "{{ item }}" 
    state: restarted
    enabled: yes
  loop:
    - graylog-server
    - nginx

# set soft link
# create link
- name: Create link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
    force: yes
  with_items:
    - {src: /usr/share/graylog-server,dest: /data/wwwroot/graylog}
    - {src: /etc/graylog,dest: /data/config}
    - {src: /etc/graylog,dest: /data/wwwroot/graylog/config}
    - {src: /var/log/graylog-server/server.log,dest: /data/logs}
    - {src: /var/log/graylog-server/server.log,dest: /data/wwwroot/graylog}
    - {src: /usr/lib/systemd/system/graylog-server.service,dest: /usr/lib/systemd/system/graylog.service}

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check Graylog Version
    shell: sudo echo "graylog `yum info graylog-server || apt show graylog-server  |grep Version |sed -n 1p`" | sudo tee -a  /data/logs/install_version.txt

# check service state
- name: Check Graylog Service
  shell: systemctl status graylog | grep Active*
  register: check_graylog_service
  notify: check_graylog_service
