- name: Delete graylog dir for sec_installation
  shell: rm -rf /data/wwwroot/graylog

- name: Clone graylog in Websoft9 
  git:
    repo: "{{graylog_git_url}}"
    dest: "/data/wwwroot/graylog"
    version: dev

- name: Create dir for graylog
  file: 
    state: directory
    path: "{{item}}"
  loop: 
    - /data/wwwroot/graylog/volumes
    - /data/db/mongodb

- name: Bind public network IP
  shell: |
    public_ip=`wget -O - https://download.websoft9.com/ansible/get_ip.sh | bash`
    sed -i "s/127.0.0.1/$public_ip/g" /data/wwwroot/graylog/docker-compose-production.yml
    
- name: Run docker-compose 
  shell: | 
    docker-compose -f docker-compose-production.yml up -d
    sleep 30
  args:
    chdir: /data/wwwroot/graylog

- name: Set soft link for graylog
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
    force: yes
  with_items:
  - {src: /data/wwwroot/graylog/volumes/mongodb/,dest: /data/db/mongodb/}

# check service and version
- name: Check graylog service 
  shell: echo "graylog" `docker inspect graylog |grep -i status`
  register: check_graylog_service
  notify: check_graylog_service
    
- name: Check graylog version
  shell: |
    sudo echo "graylog version:" $(docker images |grep graylog/graylog |awk '{print $2}') |sudo tee -a /data/logs/install_version.txt  

- name: Check mongodb version
  shell: |
    sudo echo "mongodb version:" $(docker images |grep mongo |awk '{print $2}') |sudo tee -a /data/logs/install_version.txt  

- name: Check elasticsearch version
  shell: |
    sudo echo "elasticsearch version:" $(docker images |grep elasticsearch |awk '{print $2}') |sudo tee -a /data/logs/install_version.txt  