- name: Install RPM Graylog
  yum:
    name: "{{graylog_rpm_url}}"
    
- name: Install Graylog-Server
  yum:
    name: graylog-server
    state: latest
    update_cache: yes

- name: Install Graylog Integrations Plugins or the Enterprise Plugins
  yum:
    name: [graylog-enterprise-plugins, graylog-integrations-plugins, graylog-enterprise-integrations-plugins]
    state: latest
    update_cache: yes
